// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/dht.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DHTPacketType int32

const (
	DHTPacketType_Undefined     DHTPacketType = 0
	DHTPacketType_Connect       DHTPacketType = 1
	DHTPacketType_Forward       DHTPacketType = 2
	DHTPacketType_Find          DHTPacketType = 3
	DHTPacketType_Node          DHTPacketType = 4
	DHTPacketType_Ping          DHTPacketType = 5
	DHTPacketType_RegisterProxy DHTPacketType = 6
	DHTPacketType_RequestProxy  DHTPacketType = 7
	DHTPacketType_ReportProxy   DHTPacketType = 8
	DHTPacketType_BadProxy      DHTPacketType = 9
	DHTPacketType_Proxy         DHTPacketType = 10
	DHTPacketType_Notify        DHTPacketType = 11
	DHTPacketType_ReportLoad    DHTPacketType = 12
	DHTPacketType_Stop          DHTPacketType = 13
	DHTPacketType_Unknown       DHTPacketType = 14
	DHTPacketType_DHCP          DHTPacketType = 15
	DHTPacketType_Error         DHTPacketType = 16
	DHTPacketType_Unsupported   DHTPacketType = 17
	DHTPacketType_State         DHTPacketType = 18
)

var DHTPacketType_name = map[int32]string{
	0:  "Undefined",
	1:  "Connect",
	2:  "Forward",
	3:  "Find",
	4:  "Node",
	5:  "Ping",
	6:  "RegisterProxy",
	7:  "RequestProxy",
	8:  "ReportProxy",
	9:  "BadProxy",
	10: "Proxy",
	11: "Notify",
	12: "ReportLoad",
	13: "Stop",
	14: "Unknown",
	15: "DHCP",
	16: "Error",
	17: "Unsupported",
	18: "State",
}
var DHTPacketType_value = map[string]int32{
	"Undefined":     0,
	"Connect":       1,
	"Forward":       2,
	"Find":          3,
	"Node":          4,
	"Ping":          5,
	"RegisterProxy": 6,
	"RequestProxy":  7,
	"ReportProxy":   8,
	"BadProxy":      9,
	"Proxy":         10,
	"Notify":        11,
	"ReportLoad":    12,
	"Stop":          13,
	"Unknown":       14,
	"DHCP":          15,
	"Error":         16,
	"Unsupported":   17,
	"State":         18,
}

func (x DHTPacketType) String() string {
	return proto.EnumName(DHTPacketType_name, int32(x))
}
func (DHTPacketType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dht_c6d4b1663fda0626, []int{0}
}

type DHTPacket struct {
	Type                 DHTPacketType `protobuf:"varint,1,opt,name=type,proto3,enum=main.DHTPacketType" json:"type,omitempty"`
	Id                   string        `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Infohash             string        `protobuf:"bytes,3,opt,name=infohash,proto3" json:"infohash,omitempty"`
	Data                 string        `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Query                string        `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	Arguments            []string      `protobuf:"bytes,6,rep,name=arguments,proto3" json:"arguments,omitempty"`
	Proxies              []string      `protobuf:"bytes,7,rep,name=proxies,proto3" json:"proxies,omitempty"`
	Extra                string        `protobuf:"bytes,8,opt,name=extra,proto3" json:"extra,omitempty"`
	Payload              []byte        `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	Version              int32         `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DHTPacket) Reset()         { *m = DHTPacket{} }
func (m *DHTPacket) String() string { return proto.CompactTextString(m) }
func (*DHTPacket) ProtoMessage()    {}
func (*DHTPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_dht_c6d4b1663fda0626, []int{0}
}
func (m *DHTPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DHTPacket.Unmarshal(m, b)
}
func (m *DHTPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DHTPacket.Marshal(b, m, deterministic)
}
func (dst *DHTPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DHTPacket.Merge(dst, src)
}
func (m *DHTPacket) XXX_Size() int {
	return xxx_messageInfo_DHTPacket.Size(m)
}
func (m *DHTPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_DHTPacket.DiscardUnknown(m)
}

var xxx_messageInfo_DHTPacket proto.InternalMessageInfo

func (m *DHTPacket) GetType() DHTPacketType {
	if m != nil {
		return m.Type
	}
	return DHTPacketType_Undefined
}

func (m *DHTPacket) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DHTPacket) GetInfohash() string {
	if m != nil {
		return m.Infohash
	}
	return ""
}

func (m *DHTPacket) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *DHTPacket) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *DHTPacket) GetArguments() []string {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *DHTPacket) GetProxies() []string {
	if m != nil {
		return m.Proxies
	}
	return nil
}

func (m *DHTPacket) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *DHTPacket) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *DHTPacket) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*DHTPacket)(nil), "main.DHTPacket")
	proto.RegisterEnum("main.DHTPacketType", DHTPacketType_name, DHTPacketType_value)
}

func init() { proto.RegisterFile("protocol/dht.proto", fileDescriptor_dht_c6d4b1663fda0626) }

var fileDescriptor_dht_c6d4b1663fda0626 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x49, 0x9a, 0xb4, 0xc9, 0xe9, 0x9f, 0x79, 0x07, 0x2e, 0x2c, 0xc4, 0x45, 0xc4, 0x0d,
	0x11, 0x17, 0x45, 0x82, 0x37, 0x60, 0x63, 0xda, 0x05, 0x9a, 0xaa, 0x6c, 0x7d, 0x00, 0x53, 0x9f,
	0xb6, 0xd6, 0x36, 0x9f, 0xcc, 0x71, 0x59, 0xf3, 0x08, 0x48, 0x3c, 0x34, 0xb2, 0x43, 0x87, 0xb8,
	0xfb, 0x7e, 0xbf, 0xef, 0xf8, 0x38, 0x91, 0x0c, 0xd8, 0x3a, 0xf6, 0xbc, 0xe1, 0x87, 0x4f, 0x7a,
	0xef, 0x97, 0x11, 0x30, 0x7b, 0x54, 0xc6, 0xbe, 0xff, 0x9d, 0x42, 0x79, 0x79, 0x7d, 0xb7, 0x52,
	0x9b, 0x7b, 0xf2, 0xf8, 0x01, 0x32, 0xdf, 0xb7, 0x24, 0x93, 0x2a, 0xa9, 0x17, 0x9f, 0x5f, 0x2f,
	0xc3, 0xc8, 0xf2, 0xa5, 0xbe, 0xeb, 0x5b, 0x6a, 0xe2, 0x00, 0x2e, 0x20, 0x35, 0x5a, 0xa6, 0x55,
	0x52, 0x97, 0x4d, 0x6a, 0x34, 0xbe, 0x85, 0xc2, 0xd8, 0x2d, 0xef, 0x55, 0xb7, 0x97, 0xa3, 0x68,
	0x5f, 0x18, 0x11, 0x32, 0xad, 0xbc, 0x92, 0x59, 0xf4, 0x31, 0xe3, 0x1b, 0xc8, 0x9f, 0x0e, 0xe4,
	0x7a, 0x99, 0x47, 0x39, 0x00, 0xbe, 0x83, 0x52, 0xb9, 0xdd, 0xe1, 0x91, 0xac, 0xef, 0xe4, 0xb8,
	0x1a, 0xd5, 0x65, 0xf3, 0x4f, 0xa0, 0x84, 0x49, 0xeb, 0xf8, 0x68, 0xa8, 0x93, 0x93, 0xd8, 0x9d,
	0x30, 0x6c, 0xa3, 0xa3, 0x77, 0x4a, 0x16, 0xc3, 0xb6, 0x08, 0x71, 0x5e, 0xf5, 0x0f, 0xac, 0xb4,
	0x2c, 0xab, 0xa4, 0x9e, 0x35, 0x27, 0x0c, 0xcd, 0x4f, 0x72, 0x9d, 0x61, 0x2b, 0xa1, 0x4a, 0xea,
	0xbc, 0x39, 0xe1, 0xc7, 0x5f, 0x29, 0xcc, 0xff, 0xfb, 0x5f, 0x9c, 0x43, 0xb9, 0xb6, 0x9a, 0xb6,
	0xc6, 0x92, 0x16, 0xaf, 0x70, 0x0a, 0x93, 0x0b, 0xb6, 0x96, 0x36, 0x5e, 0x24, 0x01, 0xae, 0xd8,
	0x3d, 0x2b, 0xa7, 0x45, 0x8a, 0x05, 0x64, 0x57, 0xc6, 0x6a, 0x31, 0x0a, 0xe9, 0x86, 0x35, 0x89,
	0x2c, 0xa4, 0x95, 0xb1, 0x3b, 0x91, 0xe3, 0x39, 0xcc, 0x1b, 0xda, 0x99, 0xce, 0x93, 0x5b, 0x39,
	0x3e, 0xf6, 0x62, 0x8c, 0x02, 0x66, 0x0d, 0x3d, 0x1d, 0xa8, 0xf3, 0x83, 0x99, 0xe0, 0x19, 0x4c,
	0x1b, 0x6a, 0xd9, 0xfd, 0x15, 0x05, 0xce, 0xa0, 0xf8, 0xaa, 0xf4, 0x40, 0x25, 0x96, 0x90, 0x0f,
	0x11, 0x10, 0x60, 0x7c, 0xc3, 0xde, 0x6c, 0x7b, 0x31, 0xc5, 0x05, 0xc0, 0x70, 0xea, 0x3b, 0x2b,
	0x2d, 0x66, 0xe1, 0xd2, 0x5b, 0xcf, 0xad, 0x98, 0x87, 0xef, 0x5b, 0xdb, 0x7b, 0xcb, 0xcf, 0x56,
	0x2c, 0x82, 0xbe, 0xbc, 0xbe, 0x58, 0x89, 0xb3, 0xb0, 0xe7, 0x9b, 0x73, 0xec, 0x84, 0x08, 0x37,
	0xae, 0x6d, 0x77, 0x68, 0xc3, 0x71, 0xd2, 0xe2, 0x3c, 0x74, 0xb7, 0x5e, 0x79, 0x12, 0xf8, 0x63,
	0x1c, 0xdf, 0xc9, 0x97, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x2b, 0x34, 0xcf, 0x3d, 0x02,
	0x00, 0x00,
}
