// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dht.proto

/*
Package ptp is a generated protocol buffer package.

It is generated from these files:
	dht.proto

It has these top-level messages:
	DHTPacket
*/
package ptp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DHTPacketType int32

const (
	DHTPacketType_Connect       DHTPacketType = 0
	DHTPacketType_Forward       DHTPacketType = 1
	DHTPacketType_Find          DHTPacketType = 2
	DHTPacketType_Node          DHTPacketType = 3
	DHTPacketType_Ping          DHTPacketType = 4
	DHTPacketType_RegisterProxy DHTPacketType = 5
	DHTPacketType_BadProxy      DHTPacketType = 6
	DHTPacketType_Proxy         DHTPacketType = 7
	DHTPacketType_Notify        DHTPacketType = 8
	DHTPacketType_ReportLoad    DHTPacketType = 9
	DHTPacketType_Stop          DHTPacketType = 10
	DHTPacketType_Unknown       DHTPacketType = 11
	DHTPacketType_DHCP          DHTPacketType = 12
	DHTPacketType_Error         DHTPacketType = 13
	DHTPacketType_Unsupported   DHTPacketType = 14
	DHTPacketType_State         DHTPacketType = 15
)

var DHTPacketType_name = map[int32]string{
	0:  "Connect",
	1:  "Forward",
	2:  "Find",
	3:  "Node",
	4:  "Ping",
	5:  "RegisterProxy",
	6:  "BadProxy",
	7:  "Proxy",
	8:  "Notify",
	9:  "ReportLoad",
	10: "Stop",
	11: "Unknown",
	12: "DHCP",
	13: "Error",
	14: "Unsupported",
	15: "State",
}
var DHTPacketType_value = map[string]int32{
	"Connect":       0,
	"Forward":       1,
	"Find":          2,
	"Node":          3,
	"Ping":          4,
	"RegisterProxy": 5,
	"BadProxy":      6,
	"Proxy":         7,
	"Notify":        8,
	"ReportLoad":    9,
	"Stop":          10,
	"Unknown":       11,
	"DHCP":          12,
	"Error":         13,
	"Unsupported":   14,
	"State":         15,
}

func (x DHTPacketType) String() string {
	return proto.EnumName(DHTPacketType_name, int32(x))
}
func (DHTPacketType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DHTPacket struct {
	Type      DHTPacketType `protobuf:"varint,1,opt,name=type,enum=main.DHTPacketType" json:"type,omitempty"`
	Id        string        `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Infohash  string        `protobuf:"bytes,3,opt,name=infohash" json:"infohash,omitempty"`
	Data      string        `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	Query     string        `protobuf:"bytes,5,opt,name=query" json:"query,omitempty"`
	Arguments []string      `protobuf:"bytes,6,rep,name=arguments" json:"arguments,omitempty"`
	Extra     string        `protobuf:"bytes,7,opt,name=extra" json:"extra,omitempty"`
}

func (m *DHTPacket) Reset()                    { *m = DHTPacket{} }
func (m *DHTPacket) String() string            { return proto.CompactTextString(m) }
func (*DHTPacket) ProtoMessage()               {}
func (*DHTPacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DHTPacket) GetType() DHTPacketType {
	if m != nil {
		return m.Type
	}
	return DHTPacketType_Connect
}

func (m *DHTPacket) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DHTPacket) GetInfohash() string {
	if m != nil {
		return m.Infohash
	}
	return ""
}

func (m *DHTPacket) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *DHTPacket) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *DHTPacket) GetArguments() []string {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *DHTPacket) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func init() {
	proto.RegisterType((*DHTPacket)(nil), "main.DHTPacket")
	proto.RegisterEnum("main.DHTPacketType", DHTPacketType_name, DHTPacketType_value)
}

func init() { proto.RegisterFile("dht.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x6e, 0xf2, 0x30,
	0x10, 0xc5, 0xbf, 0x40, 0x12, 0x92, 0x81, 0xc0, 0xe0, 0x6f, 0x93, 0x25, 0xed, 0x0a, 0x75, 0xc1,
	0xa2, 0xbd, 0x41, 0xa1, 0x88, 0x45, 0x85, 0x22, 0xfe, 0x1c, 0xc0, 0xc5, 0x06, 0x2c, 0x84, 0x27,
	0x75, 0x06, 0x41, 0xce, 0xd0, 0x03, 0xf6, 0x3a, 0x95, 0x83, 0x54, 0xa9, 0xbb, 0xf7, 0x9b, 0xf7,
	0xfc, 0x9e, 0x64, 0x48, 0xd5, 0x91, 0x27, 0xa5, 0x23, 0x26, 0x11, 0x9e, 0xa5, 0xb1, 0x8f, 0x5f,
	0x01, 0xa4, 0xb3, 0xc5, 0xa6, 0x90, 0xbb, 0x93, 0x66, 0xf1, 0x00, 0x21, 0xd7, 0xa5, 0xce, 0x83,
	0x51, 0x30, 0xee, 0x3f, 0xff, 0x9f, 0xf8, 0xc8, 0xe4, 0xd7, 0xde, 0xd4, 0xa5, 0x16, 0x00, 0x2d,
	0xa3, 0xf2, 0xd6, 0x28, 0x18, 0xa7, 0x02, 0x21, 0x31, 0x76, 0x4f, 0x47, 0x59, 0x1d, 0xf3, 0x76,
	0x73, 0xe9, 0x41, 0xa8, 0x24, 0xcb, 0x3c, 0x6c, 0x28, 0x83, 0xe8, 0xf3, 0xa2, 0x5d, 0x9d, 0x47,
	0x0d, 0x0e, 0x21, 0x95, 0xee, 0x70, 0x39, 0x6b, 0xcb, 0x55, 0x1e, 0x8f, 0xda, 0xf7, 0x84, 0xbe,
	0xb1, 0x93, 0x79, 0xc7, 0x27, 0x9e, 0xbe, 0x03, 0xc8, 0xfe, 0xce, 0x75, 0xa1, 0x33, 0x25, 0x6b,
	0xf5, 0x8e, 0xf1, 0x9f, 0x87, 0x39, 0xb9, 0xab, 0x74, 0x0a, 0x03, 0x91, 0x40, 0x38, 0x37, 0x56,
	0x61, 0xcb, 0xab, 0x25, 0x29, 0x8d, 0x6d, 0xaf, 0x0a, 0x63, 0x0f, 0x18, 0x8a, 0x21, 0x64, 0x2b,
	0x7d, 0x30, 0x15, 0x6b, 0x57, 0x38, 0xba, 0xd5, 0x18, 0x89, 0x1e, 0x24, 0xaf, 0x52, 0xdd, 0x29,
	0x16, 0x29, 0x44, 0x77, 0xd9, 0x11, 0x00, 0xf1, 0x92, 0xd8, 0xec, 0x6b, 0x4c, 0x44, 0x1f, 0x60,
	0xa5, 0x4b, 0x72, 0xfc, 0x4e, 0x52, 0x61, 0xea, 0x1b, 0xd7, 0x4c, 0x25, 0x82, 0x1f, 0xdf, 0xda,
	0x93, 0xa5, 0xab, 0xc5, 0xae, 0x3f, 0xcf, 0x16, 0xd3, 0x02, 0x7b, 0xbe, 0xe7, 0xcd, 0x39, 0x72,
	0x98, 0x89, 0x01, 0x74, 0xb7, 0xb6, 0xba, 0x94, 0xfe, 0xb9, 0x56, 0xd8, 0xf7, 0xde, 0x9a, 0x25,
	0x6b, 0x1c, 0x7c, 0xc4, 0xcd, 0xa7, 0xbf, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0xec, 0x4a, 0x28,
	0x6c, 0x81, 0x01, 0x00, 0x00,
}
