// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/proxy.proto

/*
Package ptp is a generated protocol buffer package.

It is generated from these files:
	protocol/proxy.proto

It has these top-level messages:
	ProxyPacket
*/
package ptp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProxyPacketType int32

const (
	ProxyPacketType_Ping     ProxyPacketType = 0
	ProxyPacketType_Register ProxyPacketType = 1
	ProxyPacketType_Discover ProxyPacketType = 2
)

var ProxyPacketType_name = map[int32]string{
	0: "Ping",
	1: "Register",
	2: "Discover",
}
var ProxyPacketType_value = map[string]int32{
	"Ping":     0,
	"Register": 1,
	"Discover": 2,
}

func (x ProxyPacketType) String() string {
	return proto.EnumName(ProxyPacketType_name, int32(x))
}
func (ProxyPacketType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ProxyPacket struct {
	Type ProxyPacketType `protobuf:"varint,1,opt,name=type,enum=main.ProxyPacketType" json:"type,omitempty"`
	Id   int32           `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Data string          `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *ProxyPacket) Reset()                    { *m = ProxyPacket{} }
func (m *ProxyPacket) String() string            { return proto.CompactTextString(m) }
func (*ProxyPacket) ProtoMessage()               {}
func (*ProxyPacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProxyPacket) GetType() ProxyPacketType {
	if m != nil {
		return m.Type
	}
	return ProxyPacketType_Ping
}

func (m *ProxyPacket) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProxyPacket) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*ProxyPacket)(nil), "main.ProxyPacket")
	proto.RegisterEnum("main.ProxyPacketType", ProxyPacketType_name, ProxyPacketType_value)
}

func init() { proto.RegisterFile("protocol/proxy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x2f, 0x28, 0xca, 0xaf, 0xa8, 0xd4, 0x03, 0x73, 0x85, 0x58, 0x72,
	0x13, 0x33, 0xf3, 0x94, 0x62, 0xb8, 0xb8, 0x03, 0x40, 0x82, 0x01, 0x89, 0xc9, 0xd9, 0xa9, 0x25,
	0x42, 0x9a, 0x5c, 0x2c, 0x25, 0x95, 0x05, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0xa2,
	0x7a, 0x20, 0x35, 0x7a, 0x48, 0x0a, 0x42, 0x2a, 0x0b, 0x52, 0x83, 0xc0, 0x4a, 0x84, 0xf8, 0xb8,
	0x98, 0x32, 0x53, 0x24, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32, 0x53, 0x84, 0x84, 0xb8,
	0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0x98, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x2d, 0x73,
	0x2e, 0x7e, 0x34, 0xcd, 0x42, 0x1c, 0x5c, 0x2c, 0x01, 0x99, 0x79, 0xe9, 0x02, 0x0c, 0x42, 0x3c,
	0x5c, 0x1c, 0x41, 0xa9, 0xe9, 0x99, 0xc5, 0x25, 0xa9, 0x45, 0x02, 0x8c, 0x20, 0x9e, 0x4b, 0x66,
	0x71, 0x72, 0x7e, 0x59, 0x6a, 0x91, 0x00, 0x53, 0x12, 0x1b, 0xd8, 0x8d, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x91, 0x91, 0x19, 0x81, 0xbb, 0x00, 0x00, 0x00,
}
