// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

/*
Package ptp is a generated protocol buffer package.

It is generated from these files:
	proxy.proto

It has these top-level messages:
	ServerPacket
*/
package ptp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PacketType int32

const (
	PacketType_Ping     PacketType = 0
	PacketType_Register PacketType = 1
	PacketType_Discover PacketType = 2
)

var PacketType_name = map[int32]string{
	0: "Ping",
	1: "Register",
	2: "Discover",
}
var PacketType_value = map[string]int32{
	"Ping":     0,
	"Register": 1,
	"Discover": 2,
}

func (x PacketType) String() string {
	return proto.EnumName(PacketType_name, int32(x))
}
func (PacketType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ServerPacket struct {
	Type PacketType `protobuf:"varint,1,opt,name=type,enum=main.PacketType" json:"type,omitempty"`
	Id   int32      `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Data string     `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *ServerPacket) Reset()                    { *m = ServerPacket{} }
func (m *ServerPacket) String() string            { return proto.CompactTextString(m) }
func (*ServerPacket) ProtoMessage()               {}
func (*ServerPacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServerPacket) GetType() PacketType {
	if m != nil {
		return m.Type
	}
	return PacketType_Ping
}

func (m *ServerPacket) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ServerPacket) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*ServerPacket)(nil), "main.ServerPacket")
	proto.RegisterEnum("main.PacketType", PacketType_name, PacketType_value)
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0xaf,
	0xa8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x8a, 0xe0,
	0xe2, 0x09, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0x0a, 0x48, 0x4c, 0xce, 0x4e, 0x2d, 0x11, 0x52, 0xe1,
	0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0x12, 0xd0, 0x03, 0x29,
	0xd2, 0x83, 0xc8, 0x85, 0x54, 0x16, 0xa4, 0x06, 0x81, 0x65, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53,
	0x24, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0x52, 0x12,
	0x4b, 0x12, 0x25, 0x98, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x2d, 0x23, 0x2e, 0x2e, 0x84,
	0x3e, 0x21, 0x0e, 0x2e, 0x96, 0x80, 0xcc, 0xbc, 0x74, 0x01, 0x06, 0x21, 0x1e, 0x2e, 0x8e, 0xa0,
	0xd4, 0xf4, 0xcc, 0xe2, 0x92, 0xd4, 0x22, 0x01, 0x46, 0x10, 0xcf, 0x25, 0xb3, 0x38, 0x39, 0xbf,
	0x2c, 0xb5, 0x48, 0x80, 0x29, 0x89, 0x0d, 0xec, 0x34, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x4a, 0xc2, 0xec, 0x0c, 0xa9, 0x00, 0x00, 0x00,
}
