#!/bin/sh

### BEGIN INIT INFO
# Provides:	  p2p
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the p2p daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/p2p
NAME=p2p
DESC=p2p

#
# Function that starts the daemon/service
#
do_start()
{
    $DAEMON daemon >/var/log/p2p-daemon.log 2>&1 &
}

#
# Function that stops the daemon/service
#
do_stop()
{
    killall -9 $NAME
}

case "$1" in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	restart)
		do_stop
		do_start
		;;
	*)
		echo "Usage: $NAME {start|stop|restart}" >&2
		exit 3
		;;
esac

:
