#!/bin/sh

systemctl status p2p.service
if [ $? -eq 0 ]; then
  systemctl stop p2p.service
  systemctl disable p2p.service
fi
systemctl unmask subutai-p2p.service
systemctl restart subutai-p2p.service

exit 0